load_check_start = "LOAD_START"
load_check_end = "LOAD_END"
font_family = 'Microsoft YaHei'
font_size = 12
server_info = ""
client_username = None
server_ip = None
server_port = None
client_name_set = "memo-LC"
# server_ip_set = '118.25.25.194'
server_ip_set = '127.0.0.1'
# server_port_set = "12672"
server_port_set = "12312"
keep_broadcasting = True
text_color_1 = 'lightblue'
text_color_2 = 'white'
desktop_width = None
desktop_height = None
