load_check_start = "LOAD_START"
load_check_end = "LOAD_END"
font_family = 'Microsoft YaHei'
font_size = 12
server_info = ""
client_username = None
server_ip = None
server_port = None
keep_broadcasting = True
